version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/php:8.2.12-browsers
    steps:
      - checkout

      # Install Composer dependencies
      - run: php /usr/local/bin/composer install

      # Run Codeception tests
      - run: ./vendor/bin/codecept run

  deploy:
    docker:
      - image: cimg/php:8.2.12-browsers
    steps:
      - checkout
      # Add steps for deploying here

# Orchestrate our job run sequence
workflows:
  version: 2

  # Run deploy job after successful test job on main branch
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
